<a href="https://colab.research.google.com/github/Mohammad-Kaif45/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.random.randint(6,16,10)
arr

array([ 6, 15,  6, 15,  9, 11, 14, 12,  8, 11])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
import numpy as np
rand_uniform = np.random.randint(1,9,5)
rand_uniform

array([8, 5, 4, 8, 5])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)   # 2 (Number of dimensions/axes)
print(arr.shape)  # (2, 3) (Rows, Columns)
print(arr.size)   # 6 (Total number of elements)
print(arr.dtype)  # float64 (Data type of elements)

2
(2, 3)
6
int64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])     # 20 (Zero-indexed)
print(arr[1:4])

# 2D Array slicing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0, 2])    # 3 (Row 0, Column 2)
print(matrix[:, 1])    # [2, 5, 8] (All rows, Column 1)
print(matrix[0:2, :2]) # [[1, 2], [4, 5]] (First two rows, first two columns)

20
[20 30 40]
3
[2 5 8]
[[1 2]
 [4 5]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
mask = arr > 3
mask_arr = arr[mask]
mask_arr
filtered_multi = arr[(arr > 2) & (arr % 2 == 0)]
print(filtered_multi) # [4, 6]

[4 6]


In [ ]:
arr = np.arange(1, 10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Reshape into a 3x3 matrix
matrix = arr.reshape(3, 3)
matrix
# Flatten back to 1D
flat = matrix.flatten()
flat
# Transpose (swap rows and columns)
transposed = matrix.T
transposed

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Global aggregations
print(np.sum(arr))  # 21
print(np.min(arr))  # 1
print(np.mean(arr)) # 3.5

# Axis-based aggregations (Axis 0 = Columns, Axis 1 = Rows)
print(np.sum(arr, axis=0)) # [5, 7, 9] (Sum of each column)
print(np.max(arr, axis=1)) # [3, 6] (Max of each row)

21
1
3.5
[5 7 9]
[3 6]


Numpy exercise

In [ ]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
s.shape

(9, 9)

In [ ]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#Get the shape of the matrix.

In [ ]:
data.shape

(5, 3)

#Find the average age of students.

In [ ]:
np.mean(data,axis=0)

array([18.4, 81.6, 83.2])

In [ ]:
average_age = np.mean(data[:, 0])
print(f"Average age of students: {average_age}")

Average age of students: 18.4


#Extract Math marks of all students.

In [ ]:
math_marks = data[:, 1]
print("Math marks of all students:")
print(math_marks)

Math marks of all students:
[85 92 76 65 90]


#Find the highest Science mark.

In [ ]:
science_mark = data[:,2]
highest_science_mark = np.max(science_mark)
print(f"Highest science mark: {highest_science_mark}")

Highest science mark: 95


#Get details of the student who scored more than 90 in Math.

In [ ]:
students_math_more_than_90 = data[data[:, 1] > 90]
print("Details of students who scored more than 90 in Math:")
print(students_math_more_than_90)

Details of students who scored more than 90 in Math:
[[19 92 88]]


#Increase Math marks of all students by 5.

In [ ]:
increased_math_marks = data[:, 1] + 5
print("Increased Math marks of all students:")
print(increased_math_marks)

Increased Math marks of all students:
[90 97 81 70 95]


#Find how many students are younger than 19.

In [ ]:
num = np.sum(data[:, 0] < 19)
print(f"Number of students younger than 19: {num}")

Number of students younger than 19: 3


#Calculate the average marks in each subject (column-wise mean).

In [ ]:
average_subject_marks = np.mean(data[:, 1:], axis=0)
print("Average marks in Math and Science:")
print(f"Math: {average_subject_marks[0]:.2f}")
print(f"Science: {average_subject_marks[1]:.2f}")

Average marks in Math and Science:
Math: 81.60
Science: 83.20


#Get data of students who scored at least 80 in both subjects.

In [ ]:
students_80_in_both = data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]
print("Details of students who scored at least 80 in both subjects:")
print(students_80_in_both)

Details of students who scored at least 80 in both subjects:
[[19 92 88]
 [20 90 85]]


#Replace all Science marks < 75 with 0.

In [ ]:
data[data[:, 2] < 75, 2] = 0
print("Data with Science marks < 75 replaced by 0:")
print(data)

Data with Science marks < 75 replaced by 0:
[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
